[general]
ipc_socket = true

[window]
decorations = "None"
opacity = 0.30

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Extra Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Extra Bold Italic" }
size = 24.0

[colors.primary]
background = "#181818"

[cursor]
hide_when_unfocused = true

[terminal]
osc52 = "OnlyCopy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "None"

[[keyboard.bindings]]
key = "J"
mods = "Alt|Shift"
mode = "~AppCursor"
chars = "\u001b[B"

[[keyboard.bindings]]
key = "J"
mods = "Alt|Shift"
mode = "AppCursor"
chars = "\u001bOB"

[[keyboard.bindings]]
key = "K"
mods = "Alt|Shift"
mode = "~AppCursor"
chars = "\u001b[A"

[[keyboard.bindings]]
key = "K"
mods = "Alt|Shift"
mode = "AppCursor"
chars = "\u001bOA"

[[keyboard.bindings]]
key = "Space"
mods = "Control|Shift"
action = "None"
