prefix = "Ctrl+a"
shell = ["sh"]
repeat_rate = 25
repeat_delay = 300
connections = []

[bindings.normal]
"Alt+h" = "focus left"
"Alt+j" = "focus down"
"Alt+k" = "focus up"
"Alt+l" = "focus right"
"Alt+H" = "workspace prev"
"Alt+L" = "workspace next"
"Alt+s" = "zoom"
"Alt+t" = "ui sessions"
"Alt+y" = "workspace last"
"Alt+Y" = "session last"

[bindings.prefix]
c = "workspace new"
"%" = "split h"
'"' = "split v"
Left = "focus left"
Down = "focus down"
Up = "focus up"
Right = "focus right"
o = "focus next"
j = "join"
x = "close"
"&" = "workspace close"
"1" = "workspace select 1"
"2" = "workspace select 2"
"3" = "workspace select 3"
"4" = "workspace select 4"
"5" = "workspace select 5"
"6" = "workspace select 6"
"7" = "workspace select 7"
"8" = "workspace select 8"
"9" = "workspace select 9"
"<" = "resize h -8"
">" = "resize h 8"
"-" = "resize v 8"
"+" = "resize v -8"
"_" = "resize v 8"
"=" = "resize v -8"
"Alt+Left" = "resize h -5"
"Alt+Right" = "resize h 5"
"Alt+Up" = "resize v -5"
"Alt+Down" = "resize v 5"
"Ctrl+Left" = "resize h -1"
"Ctrl+Right" = "resize h 1"
"Ctrl+Up" = "resize v -1"
"Ctrl+Down" = "resize v 1"
w = "ui workspaces"
s = "ui sessions"
S = "session new"
C = "ui connections"
":" = "ui command"
"," = "ui workspace-name"
"$" = "ui session-name"
P = "ui pane-name"
"?" = "ui help"
d = "detach"
Escape = "mode normal"
"Ctrl+g" = "mode normal"

[bindings.resize]
Escape = "mode normal"
"Ctrl+g" = "mode normal"
